version: 0.2

env:
  parameter-store:
    GITHUB_KEY: /CodeBuild/Github

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - mkdir -p ~/.ssh
      - echo "$GITHUB_KEY" > ~/.ssh/id_rsa
      - export GITHUB_KEY=REDACTED
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - printenv
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy -s $STAGE_NAME --region=$AWS_REGION

cache:
  paths:
    - node_modules
