service: aws-sls-typescript-api

provider:
  name: aws
  runtime: nodejs14.x
  region: 'us-east-1'

functions:
  timeInISOFormat:
    memorySize: 256
    handler: src/functions/time/index.handler
    # handler: build/functions/time/index.handler
    endpointType: regional
    timeout: 30
    events:
      - http:
          path: /time
          method: GET
          cors: true
          response:
            statusCodes:
              200:
