service: aws-sls-typescript-api

provider:
  name: aws
  runtime: nodejs14.x
  #stage: ${self:custom.stage}
  #region: ${file(env.yml):${self:custom.stage}.env.awsRegion}
  region: 'us-east-1'
  memorySize: 512

functions:
  timeInISOFormat:
    memorySize: 1024
    handler: build/functions/time/index.handler
    endpointType: regional
    timeout: 30
    events:
      - http:
          path: /time
          method: GET
          cors: true
          response:
            statusCodes:
              200:
